[build]
publish = "dist"
command = "pnpm build && pnpx edgeone pages deploy dist -n website -t $EDGEONE_API_TOKEN"

[build.environment]
NODE_VERSION = "22"

[[redirects]]
from = "/*"
to = "index.html"
status = 200

[images]
remote_images = [
  "https://github.com/.*",
  "https://img.shields.io/.*"
]
